name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install Dependencies
      run: yarn
      
    - name: Run Linters
      run: yarn lint
      
    - name: Run Tests
      run: yarn test
      
    - name: Build Application
      run: yarn build
